# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-16 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NLSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_full_name', models.CharField(max_length=200, unique=True)),
                ('subscriber_email', models.CharField(max_length=200, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='nlsubscription',
            unique_together=set([('subscriber_full_name', 'subscriber_email')]),
        ),
    ]
